# Generated by Django 5.0.2 on 2024-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
    ]
