# Generated by Django 5.0.2 on 2024-02-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_registrationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
