# Generated by Django 5.0.2 on 2024-02-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_alter_registrationcode_is_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
