# Generated by Django 5.0.2 on 2024-02-11 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_shelter_dogadoptionpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'shelter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dogadoptionpost',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gui.shelter'),
        ),
    ]
