# Generated by Django 5.0.2 on 2024-02-11 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_shelter_user_alter_dogadoptionpost_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'shelter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to=settings.AUTH_USER_MODEL),
        ),
    ]
