# Generated by Django 5.0.2 on 2024-02-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_alter_shelter_latitude_alter_shelter_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='working_hours',
            field=models.TextField(),
        ),
    ]
