# Generated by Django 5.0.2 on 2024-02-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_shelter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogadoptionpost',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Big'), ('XL', 'Extra Large')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_code',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='dogadoptionpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
