# Generated by Django 5.0.2 on 2024-02-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0012_alter_customuser_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_code',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
