# Generated by Django 5.0.2 on 2024-02-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0014_alter_customuser_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
