# Generated by Django 5.0.2 on 2024-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0015_alter_customuser_registration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogadoptionpost',
            name='adoption_stage',
            field=models.CharField(choices=[('active', 'Active'), ('in_process', 'In Process'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
