# Generated by Django 5.0.2 on 2024-02-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0018_notification_postsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gui.dogadoptionpost'),
        ),
    ]
